name: medaan_almaarifa
description: "ميدان المعرفة - تطبيق تعليمي تفاعلي"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  animate_do: ^4.2.0
  async: ^2.11.0
  audio_session: ^0.1.21
  audioplayers: ^6.5.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  freezed_annotation: ^2.4.1
  get_it: ^8.2.0
  google_fonts: ^6.3.1
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  json_annotation: ^4.9.0
  just_audio: ^0.10.5
  mailto: ^2.0.0
  mobile_scanner: ^7.1.4
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.12.0
  url_launcher: ^6.3.2
  vibration: ^3.1.6

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev
    - .env.prod
    - lang/ar.json
    - lang/en.json
    - assets/images/core/
    - assets/images/user/
    - assets/svg/
    - assets/audio/
    - assets/images/design/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpeg"
  adaptive_icon_background: "#13153b"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
